Transformers MolFeat notebook (#11)
** TODO:**
- [x] Add the actual requirements 
- [x] Polish model + fine tuning cells + text
- [x] Check the visualisations / interaction are working as expect on
PaperSpace
- [x] Fix `Run
trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b;
Error: undefined` error

---------

Co-authored-by: Alexandre Payot <18074599+payoto@users.noreply.github.com>